[versions]



[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.16.0" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.9.0" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2025.05.00" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.10.1" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version = "2.9.0" }

androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }

material-material = { group = "com.google.android.material", name = "material", version = "1.12.0" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.8.1" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version = "0.6.2" }

io-koin-core = { group = "io.insert-koin", name = "koin-core", version = "4.0.4" }
io-koin-android = { group = "io.insert-koin", name = "koin-android", version = "4.0.4" }
io-koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version = "4.0.4" }

io-coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version = "3.1.0" }
io-coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version = "3.1.0" }

squareup-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version = "2.11.0" }
squareup-converter-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version = "2.11.0" }

junit-junit = { group = "junit", name = "junit", version = "4.13.2" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.2.1" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.6.1" }

androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }



[plugins]
android-application = { id = "com.android.application", version = "8.8.2" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.1.10" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version = "2.1.10" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.1.10" }